### ISSUE TITLE
Unexpected keyword argument 'flags'

### ISSUE THREAD

**Issue by Nassz** [z00nx/reversemap#1]
Processing line 0 of ./access.log and writing to ./logTraceback (most recent call last):
  File "./reversemap.py", line 91, in <module>
    deobfuscated = deobfuscate(url)
  File "./reversemap.py", line 42, in deobfuscate
    decodedurl = re.sub(sqlkeyword, unescapedsqlkeyword, decodedurl, count=0, flags=re.IGNORECASE)
TypeError: sub() got an unexpected keyword argument 'flags'

**Comment by z00nx** [comment]
Can you share some more information like:
* Python version
* The file you are trying to parse
* Sample log file

**Comment by Nassz** [comment]
Python 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)

Nginx Access log 

8.8.8.8 - - [24/Sep/2017:09:07:46 -0400] "POST /push HTTP/1.0" 200 556 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.14 (KHTML     26 , like Gecko) Version/9.1.1 Safari/601.6.14" "8.8.8.8, 8.8.8.8"
